export const GET_FAVORITE_COLLECTION_ERROR = "GET_FAVORITE_COLLECTION_ERROR";
export const GET_FAVORITE_COLLECTION_SUCCESS =
  "GET_FAVORITE_COLLECTION_SUCCESS";
export const GET_FAVORITE_COLLECTION_PENDING =
  "GET_FAVORITE_COLLECTION_PENDING";
