export const GET_USER_COLLECTIONS_PENDING = "GET_USER_COLLECTIONS_PENDING";
export const GET_USER_COLLECTIONS_SUCCESS = "GET_USER_COLLECTIONS_SUCCESS";
export const GET_USER_COLLECTIONS_ERROR = "GET_USER_COLLECTIONS_ERROR";
