export const GET_PHOTO_DATA_PENDING = "GET_PHOTO_DATA_PENDING";
export const GET_PHOTO_DATA_SUCCESS = "GET_PHOTO_DATA_SUCCESS";
export const GET_PHOTO_DATA_ERROR = "GET_PHOTO_DATA_ERROR";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const GET_MORE_PHOTO_DATA_SUCCESS = "GET_MORE_PHOTO_DATA_SUCCESS";