export const GET_COLLECTION_PHOTO_PENDING = "GET_COLLECTION_PHOTO_PENDING";
export const GET_COLLECTION_PHOTO_SUCCESS = "GET_COLLECTION_PHOTO_SUCCESS";
export const GET_COLLECTION_PHOTO_ERROR = "GET_COLLECTION_PHOTO_ERROR";
