export const GET_FAVORITE_USER_PENDING = "GET_FAVORITE_USER_PENDING";
export const GET_FAVORITE_USER_SUCCESS = "GET_FAVORITE_USER_SUCCESS";
export const GET_FAVORITE_USER_ERROR = "GET_FAVORITE_USER_ERROR";
