export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_PENDING = "FETCH_USER_DATA_PENDING";
export const FETCH_USER_DATA_ERROR = "FETCH_USER_DATA_ERROR";
export const SET_USERNAME = "SET_USERNAME";
export const SET_FAVORITE_USERS = "SET_FAVORITE_USERS";
