export const COLLECTIONS_FETCH_COLLECTION_DATA_SUCCESS =
  "COLLECTIONS_FETCH_COLLECTION_DATA_SUCCESS";
export const COLLECTIONS_FETCH_COLLECTION_DATA_ERROR =
  "COLLECTIONS_FETCH_COLLECTION_DATA_ERROR";
export const COLLECTIONS_FETCH_COLLECTION_DATA_PENDING =
  "COLLECTIONS_FETCH_COLLECTION_DATA_PENDING";
export const GET_FAVORITES_DATA = "GET_FAVORITES_DATA";
