export const FETCH_PHOTO_PENDING = "FETCH_PHOTO_PENDING";
export const FETCH_PHOTO_ERROR = "FETCH_PHOTO_ERROR";
export const FETCH_PHOTO_SUCCESS = "FETCH_PHOTO_SUCCESS";
export const SET_FAVORITES_DATA = "SET_FAVORITES_DATA";
export const SET_FAVORITE_IMAGE = "SET_FAVORITE_IMAGE";
