export const GET_FAVORITE_PHOTOS_PENDING = "GET_FAVORITE_PHOTOS_PENDING";
export const GET_FAVORITE_PHOTOS_SUCCESS = "GET_FAVORITE_PHOTOS_SUCCESS";
export const GET_FAVORITE_PHOTOS_ERROR = "GET_FAVORITE_PHOTOS_ERROR";
