export const GET_USER_DATA_PENDING = "GET_USER_DATA_PENDING";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_ERROR = "GET_USER_DATA_ERROR";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const GET_MORE_USER_DATA_SUCCESS = "GET_MORE_USER_DATA_SUCCESS";
