export const GET_USER_PHOTOS_PENDING = "GET_USER_PHOTOS_PENDING";
export const GET_USER_PHOTOS_SUCCESS = "GET_USER_PHOTOS_SUCCESS";
export const GET_USER_PHOTOS_ERROR = "GET_USER_PHOTOS_ERROR";
export const GET_MORE_USER_PHOTOS_SUCCESS = "GET_MORE_USER_PHOTOS_SUCCESS";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
