export const GET_COLLECTION_DATA_PENDING = "GET_COLLECTION_DATA_PENDING";
export const GET_COLLECTION_DATA_SUCCESS = "GET_COLLECTION_DATA_SUCCESS";
export const GET_COLLECTION_DATA_ERROR = "GET_COLLECTION_DATA_ERROR";
export const GET_MORE_COLLECTION_DATA_SUCCESS =
  "GET_MORE_COLLECTION_DATA_SUCCESS";
export const GET_MORE_COLLECTION_DATA_END_DATA =
  "GET_MORE_COLLECTION_DATA_END_DATA";
