export const GET_COLLECTION_DATA_PENDING = "GET_COLLECTION_DATA_PENDING";
export const GET_COLLECTION_DATA_SUCCESS = "GET_COLLECTION_DATA_SUCCESS";
export const GET_COLLECTION_DATA_ERROR = "GET_COLLECTION_DATA_ERROR";
export const SET_FAVORITE_COLLECTIONS = "SET_FAVORITE_COLLECTIONS";
