export const FETCH_ALL_PHOTOS_PENDING = "FETCH_ALL_PHOTOS_PENDING";
export const FETCH_ALL_PHOTOS_ERROR = "FETCH_ALL_PHOTOS_ERROR";
export const FETCH_ALL_PHOTOS_SUCCESS = "FETCH_ALL_PHOTOS_SUCCESS";
export const SET_PARSED_DATA = "SET_PARSED_DATA";
export const SET_FAVORITES_DATA = "SET_FAVORITES_DATA";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const SET_FAVORITE_IMAGE = "SET_FAVORITE_IMAGE";